# Base configs
baseurl: "https://connorrumble.com/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: ""

# UI configs
title: "Photography by Connor Rumble"
subtitle: ""
author: "Connor Rumble"
header:
 title: "Photography"
 subtitle: "by Connor Rumble"
footer:
 name: "I'm Connor"
 bio: "future home of a bio"
 github: ""
web_design: "?"
social_urls:
  instagram: "https://www.instagram.com/21crumble.photos/"
