# Base configs
baseurl: "https://connorrumble.com"
#baseurl: "" # Comment the above line and uncomment this to test the website locally
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Connor Rumble"
subtitle: "See the world through my eyes!"
author: "Connor Rumble"
header:
 title: "Photography"
 subtitle: "by Connor Rumble"
footer:
 name: "Hey there, my name is Connor"
 bio: ""
 github: ""
web_design: ""
# Configure which exif data to display
# Tag is the actual exif tag, icon is a fontawesome icon. Use JSON notation without line breaks
exif: '[{"tag": "Model", "icon": "camera-retro"}, {"tag": "FNumber", "icon": "dot-circle-o"}, {"tag": "ExposureTime", "icon": "clock-o"}, {"tag": "ISOSpeedRatings", "icon": "info-circle"}]'
social_urls:
  instagram: "https://www.instagram.com/21crumble"
  github: "https://www.github.com/crumble21"
